version: '3.8'

services:
  document-api:
    build: .
    ports:
      - "8001:8001"
    volumes:
      # Mount the entire source directory for better file watching
      - .:/app
      # Persist marker model cache to avoid re-downloading
      - marker_cache:/home/app/.cache
    deploy:
      resources:
        limits:
          memory: 16G
        reservations:
          memory: 4G
          devices:
            - driver: nvidia
              count: 1
              capabilities: [gpu]
    environment:
      - MARKER_API_KEY=${MARKER_API_KEY:-ddVOBV7Wb1IXCCBvutoTki7sMhI5edmpYbqGeJNKuRI}
      - MARKER_API_URL=${MARKER_API_URL:-https://www.datalab.to/api/v1/marker}
      - WEAVIATE_API_KEY=${WEAVIATE_API_KEY}
      - WEAVIATE_URL=${WEAVIATE_URL}
      - GOOGLE_API_KEY=${GOOGLE_API_KEY}
      - GEMINI_API_KEY=${GOOGLE_API_KEY}
    restart: unless-stopped

volumes:
  marker_cache:
