services:
  document-api:
    build:
      context: .
      cache_from:
        - document-chunk-api:latest
    ports:
      - "8001:8001"
    volumes:
      # Mount the entire source directory for better file watching
      - .:/app
    deploy:
      resources:
        limits:
          memory: 4G
        reservations:
          memory: 1G
    environment:
      - MARKER_API_KEY=${MARKER_API_KEY:-ddVOBV7Wb1IXCCBvutoTki7sMhI5edmpYbqGeJNKuRI}
      - MARKER_API_URL=${MARKER_API_URL:-https://www.datalab.to/api/v1/marker}
      - WEAVIATE_API_KEY=${WEAVIATE_API_KEY}
      - WEAVIATE_URL=${WEAVIATE_URL}
      - GOOGLE_API_KEY=${GOOGLE_API_KEY}
      - GEMINI_API_KEY=${GOOGLE_API_KEY}
      - WEBHOOK_URL=http://webhook:3001/webhook
    restart: unless-stopped
    depends_on:
      - webhook

  webhook:
    build: ./webhook
    ports:
      - "3001:3001"
    environment:
      - PORT=3001
      - API_CALLBACK_URL=http://document-api:8001/api-callback
    restart: unless-stopped