version: '3.8'

services:
  document-api:
    environment:
      - PORT=8001
      - WEBHOOK_URL=https://${RENDER_SERVICE_NAME}.onrender.com:3000/webhook
    # Remove volumes for production
    volumes: []
    
  webhook:
    environment:
      - PORT=3000
      - API_CALLBACK_URL=http://document-api:8001/api-callback
